# -*- coding: utf-8 -*-
"""
Fallback symbol list for when Bybit API is unavailable
"""

# Lista najważniejszych symboli kryptowalutowych z Bybit
FALLBACK_SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "ADAUSDT", "DOTUSDT", "LINKUSDT",
    "LTCUSDT", "BCHUSDT", "XLMUSDT", "XRPUSDT", "EOSUSDT",
    "TRXUSDT", "ETCUSDT", "SOLUSDT", "AVAXUSDT", "MATICUSDT",
    "ATOMUSDT", "FTMUSDT", "NEARUSDT", "ALGOUSDT", "VETUSDT",
    "MANAUSDT", "SANDUSDT", "CHZUSDT", "ENJUSDT", "AXSUSDT",
    "SHIBUSDT", "DOGEUSDT", "UNIUSDT", "AAVEUSDT", "MKRUSDT",
    "COMPUSDT", "SUSHIUSDT", "YFIUSDT", "SNXUSDT", "CRVUSDT",
    "ALPHAUSDT", "OCEANUSDT", "REEFUSDT", "KLAYUSDT", "ONEUSDT",
    "HARMONYUSDT", "ZILUSDT", "RSRUSDT", "BANDUSDT", "STORJUSDT",
    "SKLUSDT", "ANKRUSDT", "CTKUSDT", "LITUSDT", "UNFIUSDT",
    "DUSKUSDT", "BELUSDT", "WINGUSDT", "KNCUSDT", "DEFIUSDT",
    "AUDIOUSDT", "CVCUSDT", "CTSIUSDT", "QUICKUSDT", "STMXUSDT",
    "HBARUSDT", "MDTUSDT", "STXUSDT", "ZENUSDT", "OMGUSDT",
    "NKNUSDT", "SCUSDT", "DGBUSDT", "1INCHUSDT", "CHRUSDT",
    "MANAUSDT", "ICPUSDT", "DFUSDT", "FILUSDT", "TLMUSDT",
    "ROSEUSDT", "KSMUSDT", "EGLDUSDT", "DIAUSDT", "FLOWUSDT",
    "MASKUSDT", "THETAUSDT", "RUNAUSDT", "BAKEUSDT", "BURGERUSDT",
    "SLPUSDT", "FTTUSDT", "SRMUSDT", "RAYUSDT", "C98USDT",
    "GALAUSDT", "ILVUSDT", "YGGUSDT", "FIDAUSDT", "FRONTUSDT",
    "CVPUSDT", "AGLDUSDT", "RADUSDT", "BETAUSDT", "RAREUSDT",
    "LAZIOUSDT", "ADXUSDT", "AUCTIONUSDT", "DARUSDT", "BNXUSDT",
    "RGTUSDT", "MOVRUSDT", "CITYUSDT", "ENSUSDT", "KP3RUSDT",
    "QIUSDT", "PORTOUSDT", "POWRUSDT", "VGXUSDT", "JASMYUSDT",
    "AMPUSDT", "PYRUSDT", "BICOUSDT", "FLUXUSDT", "FXSUSDT",
    "VOXELUSDT", "HIGHUSDT", "CVXUSDT", "PEOPLEUSDT", "OOKIUSDT",
    "SPELLUSDT", "1000SATSUSDT", "ORDIUSDT", "KASUSDT", "BONKUSDT",
    "ARKMUSDT", "WIFUSDT", "JUPUSDT", "PYTHUSDT", "TNSRUSDT",
    "AIUSDT", "ALTUSDT", "MANTAUSDT", "OPUSDT", "ARBUSDT",
    "INJUSDT", "STRKUSDT", "PIXELUSDT", "PORTALUSDT", "AXLUSDT",
    "MYROUSDT", "METISUSDT", "AEVOUSDT", "VANRYUSDT", "BOMEUSDT",
    "ETHFIUSDT", "ENAUSDT", "WUSDT", "TAOUSDT", "OMNIUSDT",
    "REZUSDT", "BBUSDT", "NOTUSDT", "IOUSDT", "ZKUSDT",
    "ZROUSDT", "GUSDT", "RENDERUSDT", "TONUSDT", "DOGSUSDT"
]

def get_fallback_symbols():
    """Zwraca listę fallback symboli gdy Bybit API nie działa"""
    return FALLBACK_SYMBOLS.copy()

def is_fallback_symbol(symbol):
    """Sprawdza czy symbol jest w liście fallback"""
    return symbol in FALLBACK_SYMBOLS